# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"logger": "00_core.ipynb",
         "tc": "00_core.ipynb",
         "get_query_features_df": "00_core.ipynb",
         "Curator": "00_core.ipynb",
         "AbsBoundariesCurator": "00_core.ipynb",
         "RelBoundariesCurator": "00_core.ipynb"}

modules = ["curator.py"]

doc_url = "https://jonilaserson.github.io/curation_magic/"

git_url = "https://github.com/jonilaserson/curation_magic/tree/master/"

def custom_doc_links(name): return None
